name: Action - Deploy Storybook
on:
  push:
    branches:
      -main
jobs:
  Deploy Storybook:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
              node-version: 'lts/*',
        - run: yarn deploy